
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//
// I want to compare the mixed showers to those generated by   //
// Geant4 in order to check whether the 'mixing' method I have //
// come up with is good enough.                                //
//-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-//

#include "myHist.C"

int m_nEvent = 100;

TString savedir = "../plots/MixComparison/";

//----------------------------------------//
// Main
//----------------------------------------//
void CompareMix()
{

  // Specify the input file for mixed files
  //TFile* f_mix = new TFile("../output/mixedShower_Eprim40_ToBeMixed100_nEvents100.root");
  //TFile* f_mix = new TFile("../output/mixedShower_Eprim40_ToBeMixed1000_nEvents100.root");
  TFile* f_mix = new TFile("../output/mixedShower_Eprim40_ToBeMixed100scale10_nEvents100.root");

  // Specify the input file for G4 showers
  //TFile* f_g4  = new TFile("../../IceBlock/rootfiles/LowEnergyStudy_40_ice_eBeam_np100.root");
  TFile* f_g4  = new TFile("../../IceBlock/rootfiles/LowEnergyStudy_40_ice_eBeam_np1000.root");

  // What to save as
  //TString append = "DepthComparison_Ebeam40MeV_nprimary100";
  //TString append = "DepthComparison_Ebeam40MeV_nprimary1000";
  TString append = "DepthComparison_Ebeam40MeV_nprimary100scale10";

  plot(f_mix, f_g4, append);
  
}

//----------------------------------------//
// Plot Two histograms
//----------------------------------------//
void plot(TFile* f_mix, TFile* f_g4, TString append)
{

  // Make Canvas
  TCanvas* c = makeCanvas("c");
  c->SetLogy();

  // Make Legend
  TLegend* leg = makeLegend(0.7,0.9,0.75,0.92);
  leg->SetTextSize(0.05);

  // Some plot particles
  TString xtitle = "Shower Depth [cm]";
  TString ytitle = "<N(e^{-}-e^{+})>";

  // Get profile from g4 results
  //TProfile* p_g4 = getProfile(f_g4,"NPartSum",xtitle,ytitle,kBlack,20);
  TProfile* p_g4 = getProfile(f_g4,"NPartDiff",xtitle,ytitle,kBlack,20);
  p_g4->SetMarkerSize(0.75);

  // Get profile from mixed file
  int nbins = p_g4->GetNbinsX();
  float xmin = p_g4->GetXaxis()->GetXmin();
  float xmax = p_g4->GetXaxis()->GetXmax();
  TProfile* p_mix = getMixProfile(f_mix,nbins,xmin,xmax,kBlue,25);

  // Add to legend
  leg->AddEntry(p_g4,"G4", "lep");
  leg->AddEntry(p_mix,"G4 Mixed", "lep");

  // Draw
  //p_g4->Draw();
  //p_mix->Draw("same");
  //leg->Draw("same");

  // Make ratio plot
  plotRatio(p_mix, p_g4, leg, c, "Mixed/G4", append);

}

//----------------------------------------//
// Make ratio plot
//----------------------------------------//
void plotRatio(TProfile* p0,
	       TProfile* p1,
	       TLegend* leg,
	       TCanvas* c,
	       string title,
	       TString append)
{

  // Make TPad object
  TPad* p_top;
  TPad* p_bot;
  makePads(c,p_top,p_bot);

  // Plot stuff on top
  c->cd();
  p_top->Draw();
  p_top->cd();
  p_top->SetLogy();
  
  // Set Some attributes
  p1->SetLabelSize(0.0,"X");
  p1->SetLabelSize(0.06, "Y");
  p1->GetYaxis()->SetTitleSize(0.06);
  p1->GetYaxis()->SetTitleOffset(0.85);

  // Draw Top
  p1->Draw();
  p0->Draw("same");
  leg->Draw("same");
  p_top->Update();

  // Get Bottom objects
  TH1D* ratio = getRatio(p0,p1,title);
  float xmax  = ratio->GetXaxis()->GetXmax();
  TLine* mid  = makeLine(0,xmax,1.0,1.0);
  TLine* u50  = makeLine(0,xmax,1.5,1.5,kBlack,2);
  TLine* d50  = makeLine(0,xmax,0.5,0.5,kBlack,2);


  // Draw bottom
  c->cd();
  p_bot->Draw();
  p_bot->cd();

  // Draw bottom objects
  ratio->Draw("ep");
  mid->Draw("same");
  u50->Draw("same");
  d50->Draw("same");
  ratio->Draw("sameep");
  p_bot->Update();


  c->SaveAs(savedir+append+".png");

}

//----------------------------------------//
// Make ratio of profiles
//----------------------------------------//
TH1D* getRatio(TProfile* p0, TProfile* p1,
	       string title)
{

  TH1D* h0 = p0->ProjectionX();
  TH1D* h1 = p1->ProjectionX();
  h0->Divide(h1);
  h0->GetXaxis()->SetTitle(p1->GetXaxis()->GetTitle());
  h0->GetYaxis()->SetTitle(title.c_str());
  h0->SetMaximum(2);
  h0->SetMinimum(0);
  h0->SetStats(0);
  h0->GetXaxis()->SetTitleSize(0.12);
  h0->GetYaxis()->SetTitleSize(0.15);
  h0->GetXaxis()->SetTitleOffset(1.2);
  h0->GetYaxis()->SetTitleOffset(0.35);
  h0->GetYaxis()->CenterTitle();
  h0->SetLabelSize(0.12,"X");
  h0->SetLabelSize(0.12,"Y");
  h0->GetYaxis()->SetNdivisions(405);

  return h0;

}

//----------------------------------------//
// Get profile from all events mixed
//----------------------------------------//
TProfile* getMixProfile(TFile* file, int nbins,
			float xmin, float xmax,
			int color, int marker)
{

  // Histograms all have same base name
  string base = "h_evt";
  
  // String stream easy for manipulation
  stringstream ss;
  
  // Create Profile
  TProfile* p = new TProfile("mixed","",nbins,xmin,xmax);
  p->SetMarkerSize(0.75);
  p->SetMarkerStyle(marker);
  p->SetMarkerColor(color);
  p->SetLineColor(color);

  // Now loop over events and get result
  TH1F* h = NULL;
  for(int i=0; i<m_nEvent; ++i){
    ss.str("");
    ss << base << i;
    h = (TH1F*) file->Get(ss.str().c_str());

    // Loop over bin content
    for(int bin=1; bin<=h->GetNbinsX(); ++bin){
      float content = h->GetBinContent(bin);
      float center  = h->GetBinCenter(bin);
      p->Fill(center, content);
    }
    
    h = NULL;

  }// end loop events

  return p;

}
